package com.greyhammer.erpservice.models;

public enum TaskType {
    FOR_ARCHITECTURAL_DESIGN,
    DEFINE_SCOPE_OF_WORK,
    PRICE_CANVASSING,
    SCHEDULE_PROJECT,
    COST_ESTIMATE_APPROVAL,
    ACCOUNTING_APPROVAL,
    STATEKHOLDER_APPROVAL,
    CLIENT_APPROVAL,
    MATERIAL_REQUEST_APPROVAL,
    MATERIAL_REQUEST_APPROVAL_CE,
    PROGRESS_APPROVAL,
    PROGRESS_APPROVAL_CE,
    FOR_PURCHASE_ORDER
}
